/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alessandra
 */
public class CFFrame5 extends javax.swing.JFrame {

    /**
     * Creates new form CFFrame5
     */
    public CFFrame5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel88 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel89 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel92 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel95 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setLayout(null);

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("LUXE PALACE HOTEL");
        jPanel10.add(jLabel63);
        jLabel63.setBounds(10, 10, 300, 50);

        jLabel64.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Indulge in opulence and sophistication, where impeccable service and lavish amenities redefine luxury hospitality");
        jPanel10.add(jLabel64);
        jLabel64.setBounds(310, 20, 1214, 30);

        jPanel1.add(jPanel10);
        jPanel10.setBounds(0, 0, 1300, 80);

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HOTEL1 (1) (1).jpg"))); // NOI18N
        jPanel1.add(jLabel65);
        jLabel65.setBounds(0, 70, 270, 130);

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POOL (1) (1).jpg"))); // NOI18N
        jPanel1.add(jLabel66);
        jLabel66.setBounds(270, 80, 260, 120);

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOBBY (1) (1).jpeg"))); // NOI18N
        jPanel1.add(jLabel67);
        jLabel67.setBounds(520, 80, 250, 120);

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BUFFET (1).jpg"))); // NOI18N
        jPanel1.add(jLabel68);
        jLabel68.setBounds(740, 80, 250, 120);

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocean.jpg"))); // NOI18N
        jPanel1.add(jLabel69);
        jLabel69.setBounds(980, 80, 320, 120);

        jLabel70.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel70.setText("Thank you for choosing Luxe Palace Hotel! Your reservation has been successfully processed, and we are delighted to confirm your booking. ");
        jPanel1.add(jLabel70);
        jLabel70.setBounds(60, 220, 1270, 32);

        jPanel11.setBackground(new java.awt.Color(204, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setLayout(null);

        jLabel71.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel71.setText("Reservation Number: ");
        jPanel11.add(jLabel71);
        jLabel71.setBounds(20, 50, 150, 20);

        jLabel72.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel72.setText("Name: ");
        jPanel11.add(jLabel72);
        jLabel72.setBounds(20, 80, 60, 30);

        jLabel73.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel73.setText("Address: ");
        jPanel11.add(jLabel73);
        jLabel73.setBounds(20, 120, 70, 30);

        jLabel74.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel74.setText("Reservation details");
        jPanel11.add(jLabel74);
        jLabel74.setBounds(10, 0, 140, 40);

        jLabel75.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel75.setText("Room Type:");
        jPanel11.add(jLabel75);
        jLabel75.setBounds(20, 160, 160, 30);

        jLabel76.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel76.setText("Check-In Day and Time: ");
        jPanel11.add(jLabel76);
        jLabel76.setBounds(430, 70, 180, 50);

        jPanel12.setLayout(null);
        jPanel12.add(jLabel79);
        jLabel79.setBounds(0, 0, 250, 30);

        jPanel11.add(jPanel12);
        jPanel12.setBounds(170, 40, 250, 30);

        jPanel14.setLayout(null);
        jPanel14.add(jLabel80);
        jLabel80.setBounds(0, 0, 350, 30);

        jPanel11.add(jPanel14);
        jPanel14.setBounds(70, 80, 350, 30);

        jPanel15.setLayout(null);
        jPanel15.add(jLabel81);
        jLabel81.setBounds(0, 0, 340, 30);

        jPanel11.add(jPanel15);
        jPanel15.setBounds(80, 120, 340, 30);

        jPanel16.setLayout(null);
        jPanel16.add(jLabel82);
        jLabel82.setBounds(0, 0, 220, 30);

        jPanel11.add(jPanel16);
        jPanel16.setBounds(110, 160, 310, 30);

        jPanel17.setLayout(null);
        jPanel17.add(jLabel83);
        jLabel83.setBounds(0, 0, 200, 30);

        jPanel11.add(jPanel17);
        jPanel17.setBounds(590, 80, 200, 30);

        jLabel85.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel85.setText("Number of Guest:");
        jPanel11.add(jLabel85);
        jLabel85.setBounds(430, 30, 220, 50);

        jPanel18.setLayout(null);
        jPanel18.add(jLabel86);
        jLabel86.setBounds(0, 0, 240, 30);

        jPanel11.add(jPanel18);
        jPanel18.setBounds(550, 40, 240, 30);

        jLabel78.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel78.setText("Additional information:");
        jPanel11.add(jLabel78);
        jLabel78.setBounds(10, 220, 180, 30);

        jLabel87.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel87.setText("Payment Method:");
        jPanel11.add(jLabel87);
        jLabel87.setBounds(820, 40, 130, 30);

        jPanel19.setLayout(null);

        jLabel88.setText("jLabel79");
        jPanel19.add(jLabel88);
        jLabel88.setBounds(0, 0, 210, 30);

        jPanel11.add(jPanel19);
        jPanel19.setBounds(170, 40, 250, 30);

        jPanel20.setLayout(null);
        jPanel20.add(jLabel89);
        jLabel89.setBounds(0, 0, 260, 30);

        jPanel11.add(jPanel20);
        jPanel20.setBounds(940, 40, 260, 30);

        jPanel21.setLayout(null);

        jLabel90.setText("jLabel79");
        jPanel21.add(jLabel90);
        jLabel90.setBounds(0, 0, 210, 30);

        jPanel11.add(jPanel21);
        jPanel21.setBounds(940, 40, 250, 30);

        jLabel91.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel91.setText("Total Amount Paid:");
        jPanel11.add(jLabel91);
        jLabel91.setBounds(820, 80, 130, 30);

        jPanel22.setLayout(null);
        jPanel22.add(jLabel92);
        jLabel92.setBounds(0, 0, 210, 30);

        jPanel11.add(jPanel22);
        jPanel22.setBounds(950, 80, 250, 30);

        jPanel23.setLayout(null);

        jLabel93.setText("jLabel79");
        jPanel23.add(jLabel93);
        jLabel93.setBounds(0, 0, 210, 30);

        jPanel11.add(jPanel23);
        jPanel23.setBounds(950, 80, 250, 30);

        jLabel94.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel94.setText("Confirmation Number:");
        jPanel11.add(jLabel94);
        jLabel94.setBounds(820, 120, 170, 30);

        jPanel24.setLayout(null);
        jPanel24.add(jLabel95);
        jLabel95.setBounds(0, 0, 230, 30);

        jPanel11.add(jPanel24);
        jPanel24.setBounds(970, 120, 230, 30);

        jPanel25.setLayout(null);

        jLabel96.setText("jLabel79");
        jPanel25.add(jLabel96);
        jLabel96.setBounds(0, 0, 210, 30);

        jPanel11.add(jPanel25);
        jPanel25.setBounds(970, 120, 230, 30);

        jLabel97.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel97.setText("Check-Out Day and Time: ");
        jPanel11.add(jLabel97);
        jLabel97.setBounds(430, 110, 180, 50);

        jPanel26.setLayout(null);
        jPanel26.add(jLabel98);
        jLabel98.setBounds(0, 0, 180, 30);

        jPanel11.add(jPanel26);
        jPanel26.setBounds(610, 120, 180, 30);

        jLabel99.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel99.setText("Payment Information:");
        jPanel11.add(jLabel99);
        jLabel99.setBounds(820, 0, 160, 40);

        jLabel100.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel100.setText("Should you have any questions or require further assistance, please do not hesitate to contact our customer service team at 012 - 345 - 6789 or email LuxePalaceHotel123@email.com.");
        jPanel11.add(jLabel100);
        jLabel100.setBounds(10, 260, 1230, 30);

        jLabel101.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel101.setText("We look forward to welcoming you to Luxe Palace Hotel and ensuring your stay is both comfortable and memorable.");
        jPanel11.add(jLabel101);
        jLabel101.setBounds(10, 290, 880, 21);

        jLabel102.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel102.setText("Check-in Instructions: Please present your confirmation email at the reception desk upon arrival to expedite the check-in process.");
        jPanel11.add(jLabel102);
        jLabel102.setBounds(180, 220, 880, 30);

        jLabel77.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel77.setText("Warm Regards, Luxe Palace Hotel.");
        jPanel11.add(jLabel77);
        jLabel77.setBounds(10, 320, 250, 21);

        jPanel1.add(jPanel11);
        jPanel11.setBounds(20, 310, 1270, 360);

        jLabel84.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel84.setText("\"Experience Comfort and Luxury\"");
        jPanel1.add(jLabel84);
        jLabel84.setBounds(480, 250, 290, 32);

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setText("Exit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(1220, 690, 70, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        RegFrame1 form1 = new RegFrame1();

        setVisible(false);

        form1.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CFFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CFFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CFFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CFFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CFFrame5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    // End of variables declaration//GEN-END:variables
}
