/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alessandra
 */
public class HRFrame6 extends javax.swing.JFrame {

    /**
     * Creates new form HRFrame6
     */
    public HRFrame6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane8 = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPane9 = new javax.swing.JTextPane();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextPane10 = new javax.swing.JTextPane();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextPane11 = new javax.swing.JTextPane();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextPane12 = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane7 = new javax.swing.JTextPane();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextPane13 = new javax.swing.JTextPane();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextPane14 = new javax.swing.JTextPane();
        jLabel25 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextPane15 = new javax.swing.JTextPane();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextPane16 = new javax.swing.JTextPane();
        jButton3 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LUXE PALACE HOTEL");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 10, 300, 50);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Indulge in opulence and sophistication, where impeccable service and lavish amenities redefine luxury hospitality");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(310, 20, 1214, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1300, 80);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setText("Hotel Reservation Form");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(490, 80, 500, 60);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Please fill in this Hotel Reservation Form to book a room for the period you would like to stay.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 130, 700, 20);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("Reservation Details");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 270, 220, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Phone Number");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(350, 170, 140, 40);

        jScrollPane1.setViewportView(jTextPane1);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(350, 210, 270, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Age");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(530, 40, 150, 40);

        jScrollPane2.setViewportView(jTextPane2);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(530, 80, 80, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Last Name");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 50, 140, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("First Name");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(180, 40, 140, 40);

        jScrollPane3.setViewportView(jTextPane3);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(10, 80, 160, 30);

        jScrollPane4.setViewportView(jTextPane4);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(180, 80, 160, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Middle Name");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(350, 40, 140, 40);

        jScrollPane5.setViewportView(jTextPane5);

        jPanel4.add(jScrollPane5);
        jScrollPane5.setBounds(350, 80, 160, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Address");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(10, 110, 140, 30);

        jScrollPane6.setViewportView(jTextPane6);

        jPanel4.add(jScrollPane6);
        jScrollPane6.setBounds(10, 140, 600, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Email Address ");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(10, 170, 140, 40);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Check-In Date");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(10, 300, 140, 40);

        jScrollPane8.setViewportView(jTextPane8);

        jPanel4.add(jScrollPane8);
        jScrollPane8.setBounds(10, 210, 330, 30);

        jScrollPane9.setViewportView(jTextPane9);

        jPanel4.add(jScrollPane9);
        jScrollPane9.setBounds(10, 340, 100, 30);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel19.setText("Guest Information");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(10, 10, 220, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Check-Out Time");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(150, 300, 140, 40);

        jScrollPane10.setViewportView(jTextPane10);

        jPanel4.add(jScrollPane10);
        jScrollPane10.setBounds(150, 340, 100, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Check-In Date");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(300, 300, 140, 40);

        jScrollPane11.setViewportView(jTextPane11);

        jPanel4.add(jScrollPane11);
        jScrollPane11.setBounds(300, 340, 100, 30);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Check-Out Date");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(450, 300, 140, 40);

        jScrollPane12.setViewportView(jTextPane12);

        jPanel4.add(jScrollPane12);
        jScrollPane12.setBounds(450, 340, 100, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 170, 630, 440);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Kids");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(120, 30, 50, 30);

        jScrollPane7.setViewportView(jTextPane7);

        jPanel3.add(jScrollPane7);
        jScrollPane7.setBounds(120, 60, 90, 30);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel21.setText("Number of Guest");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(10, 10, 150, 21);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Adult");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(10, 30, 50, 30);

        jScrollPane13.setViewportView(jTextPane13);

        jPanel3.add(jScrollPane13);
        jScrollPane13.setBounds(10, 60, 90, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel13.setText("Room Type");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(250, 10, 140, 21);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Single Room", "Double Room", "Family Suite", "VIP Room 1", "VIP Room 2", "Executive Room", "Deluxe Suit", "Penthouse" }));
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(250, 40, 300, 50);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Special Request");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(10, 100, 190, 20);

        jScrollPane14.setViewportView(jTextPane14);

        jPanel3.add(jScrollPane14);
        jScrollPane14.setBounds(10, 122, 570, 30);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel25.setText("Preferences");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(40, 161, 120, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ground Floor", "Middle Floors", "Higher Floors" }));
        jPanel3.add(jComboBox2);
        jComboBox2.setBounds(300, 160, 140, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Smoking Room", "Non-Smoking Room" }));
        jPanel3.add(jComboBox3);
        jComboBox3.setBounds(140, 160, 150, 30);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "City View", "Ocean View", "Garden View" }));
        jPanel3.add(jComboBox4);
        jComboBox4.setBounds(450, 160, 140, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Additional Services");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 200, 160, 30);

        jCheckBox1.setText("Room Service");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox1);
        jCheckBox1.setBounds(450, 200, 170, 30);

        jCheckBox2.setText("Breakfast");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox2);
        jCheckBox2.setBounds(170, 200, 90, 30);

        jCheckBox3.setText("Spa Package");
        jPanel3.add(jCheckBox3);
        jCheckBox3.setBounds(260, 200, 100, 30);

        jCheckBox4.setText("Hotel Tour");
        jPanel3.add(jCheckBox4);
        jCheckBox4.setBounds(360, 200, 90, 30);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel23.setText("Payment Information");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(10, 240, 220, 21);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Mode of Payment");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(10, 270, 150, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Credit Card", "Debit Card", "Online Payment", "Gcash" }));
        jPanel3.add(jComboBox5);
        jComboBox5.setBounds(10, 300, 270, 30);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Enter Amount");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(300, 270, 180, 20);

        jScrollPane15.setViewportView(jTextPane15);

        jPanel3.add(jScrollPane15);
        jScrollPane15.setBounds(300, 300, 280, 30);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("Enter Amount");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(300, 270, 180, 20);

        jScrollPane16.setViewportView(jTextPane16);

        jPanel3.add(jScrollPane16);
        jScrollPane16.setBounds(300, 300, 280, 30);

        jButton3.setBackground(new java.awt.Color(102, 153, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Hotel Reservation");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(990, 770, 170, 40);

        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Call or Text 012 - 345 - 6789");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(10, 390, 160, 16);

        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("For reservations or inquiries, please contact us at  LuxePalaceHotel123@email.com");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(10, 400, 650, 30);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setText("For more information or request message us to the following:");
        jPanel3.add(jLabel31);
        jLabel31.setBounds(10, 370, 490, 20);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setText("Note: 500 pesos per person");
        jPanel3.add(jLabel32);
        jLabel32.setBounds(440, 230, 160, 16);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(670, 170, 610, 440);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1190, 650, 90, 30);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setText("Hotel Rooms");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 650, 180, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        HRFrame6 form6 = new HRFrame6();

        setVisible(false);

        form6.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CFFrame5 form5 = new CFFrame5();

        setVisible(false);

        form5.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        HRFrame4 form4 = new HRFrame4();

        setVisible(false);

        form4.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRFrame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRFrame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRFrame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRFrame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRFrame6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane10;
    private javax.swing.JTextPane jTextPane11;
    private javax.swing.JTextPane jTextPane12;
    private javax.swing.JTextPane jTextPane13;
    private javax.swing.JTextPane jTextPane14;
    private javax.swing.JTextPane jTextPane15;
    private javax.swing.JTextPane jTextPane16;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JTextPane jTextPane7;
    private javax.swing.JTextPane jTextPane8;
    private javax.swing.JTextPane jTextPane9;
    // End of variables declaration//GEN-END:variables
}
