/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alessandra
 */
public class HRFrame4 extends javax.swing.JFrame {

    /**
     * Creates new form HRFrame4
     */
    public HRFrame4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel19 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 680));
        setResizable(false);
        setSize(new java.awt.Dimension(1300, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setPreferredSize(new java.awt.Dimension(1300, 680));
        jPanel19.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LUXE PALACE HOTEL");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 10, 300, 50);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Indulge in opulence and sophistication, where impeccable service and lavish amenities redefine luxury hospitality");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(310, 20, 1214, 30);

        jPanel19.add(jPanel2);
        jPanel2.setBounds(0, 0, 1310, 80);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setText("Luxe Palace Hotel Rooms");
        jPanel19.add(jLabel2);
        jLabel2.setBounds(480, 80, 370, 60);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("\"Experience Comfort and Luxury\"");
        jPanel19.add(jLabel5);
        jLabel5.setBounds(480, 122, 350, 50);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel29.setText("BOOK NOW!");
        jPanel19.add(jLabel29);
        jLabel29.setBounds(1070, 110, 181, 41);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viproom (1).jpg"))); // NOI18N
        jPanel19.add(jLabel31);
        jLabel31.setBounds(680, 400, 300, 200);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/single room (2) (1).jpg"))); // NOI18N
        jPanel19.add(jLabel32);
        jLabel32.setBounds(10, 180, 300, 200);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/family room (1).jpeg"))); // NOI18N
        jPanel19.add(jLabel30);
        jLabel30.setBounds(10, 400, 300, 200);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/double room (2).jpg"))); // NOI18N
        jPanel19.add(jLabel33);
        jLabel33.setBounds(680, 180, 300, 200);

        jLabel6.setText("Indulge in serenity with our Solo Retreat Package, offering ");
        jLabel6.setToolTipText("");
        jPanel19.add(jLabel6);
        jLabel6.setBounds(330, 250, 320, 16);

        jLabel7.setText(" luxurious accommodation in our Single Room and a complimentary ");
        jPanel19.add(jLabel7);
        jLabel7.setBounds(310, 270, 370, 16);

        jLabel8.setText("spa credit for ultimate relaxation. Experience refined");
        jPanel19.add(jLabel8);
        jLabel8.setBounds(340, 290, 280, 16);

        jLabel9.setText("comfort and personalized service at Luxe Palace Hotel.      ");
        jPanel19.add(jLabel9);
        jLabel9.setBounds(340, 310, 310, 16);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Single Room");
        jPanel3.add(jLabel10);

        jPanel19.add(jPanel3);
        jPanel3.setBounds(380, 190, 210, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("₱2,000 Per Day!");
        jPanel19.add(jLabel11);
        jLabel11.setBounds(410, 220, 150, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BOOK NOW!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton1);
        jButton1.setBounds(400, 340, 170, 32);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Double Room");
        jPanel4.add(jLabel12);

        jPanel19.add(jPanel4);
        jPanel4.setBounds(1030, 180, 210, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("₱3,000 Per Day!");
        jPanel19.add(jLabel13);
        jLabel13.setBounds(1060, 220, 150, 30);

        jLabel14.setText(" Relax in our Double Room at Luxe Palace Hotel, where ");
        jLabel14.setToolTipText("");
        jPanel19.add(jLabel14);
        jLabel14.setBounds(1000, 250, 300, 16);

        jLabel15.setText("comfort meets luxury for your perfect stay. Experience ");
        jPanel19.add(jLabel15);
        jLabel15.setBounds(1000, 270, 290, 16);

        jLabel16.setText("the best in relaxation and style during your getaway.      ");
        jPanel19.add(jLabel16);
        jLabel16.setBounds(1010, 290, 370, 16);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BOOK NOW!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton2);
        jButton2.setBounds(1050, 330, 170, 32);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Family Room");
        jPanel5.add(jLabel17);

        jPanel19.add(jPanel5);
        jPanel5.setBounds(380, 410, 210, 30);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("₱4,000 Per Day!");
        jPanel19.add(jLabel18);
        jLabel18.setBounds(410, 450, 150, 30);

        jLabel19.setText("Unwind in our Family Room at Luxe Palace Hotel,");
        jLabel19.setToolTipText("");
        jPanel19.add(jLabel19);
        jLabel19.setBounds(350, 480, 270, 16);

        jLabel20.setText("where comfort and style await your family's perfect retreat. ");
        jPanel19.add(jLabel20);
        jLabel20.setBounds(340, 500, 320, 16);

        jLabel21.setText("Enjoy a memorable stay in our spacious and cozy accommodations.      ");
        jPanel19.add(jLabel21);
        jLabel21.setBounds(320, 520, 380, 16);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BOOK NOW!");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton3);
        jButton3.setBounds(400, 560, 170, 32);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("VIP ROOM 1");
        jPanel6.add(jLabel22);

        jPanel19.add(jPanel6);
        jPanel6.setBounds(1030, 410, 210, 30);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("₱5,000 Per Day!");
        jPanel19.add(jLabel23);
        jLabel23.setBounds(1060, 450, 150, 30);

        jLabel24.setText(" Indulge in exclusivity at Luxe Palace Hotel's VIP Room 1,");
        jLabel24.setToolTipText("");
        jPanel19.add(jLabel24);
        jLabel24.setBounds(990, 490, 310, 16);

        jLabel25.setText("where luxury and sophistication ensure an unforgettable stay.");
        jPanel19.add(jLabel25);
        jLabel25.setBounds(980, 510, 330, 16);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BOOK NOW!");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton4);
        jButton4.setBounds(1050, 560, 170, 32);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Main Menu");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton5);
        jButton5.setBounds(10, 620, 140, 27);

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setText("More Rooms");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton6);
        jButton6.setBounds(1140, 620, 140, 27);

        getContentPane().add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HRFrame6 form6 = new HRFrame6();
        
        setVisible(false);
        
        form6.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        HRFrame6 form6 = new HRFrame6();
        
        setVisible(false);
        
        form6.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         HRFrame6 form6 = new HRFrame6();
        
        setVisible(false);
        
        form6.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         HRFrame6 form6 = new HRFrame6();
        
        setVisible(false);
        
        form6.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        MMFrame3 form3 = new MMFrame3();
        
        setVisible(false);
        
        form3.setVisible(true); 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       LoginFrame2 form2 = new LoginFrame2();
        
        setVisible(false);
        
        form2.setVisible(true); 
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRFrame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
